// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// postsDao is the data access object for the table posts.
// You can define custom methods on it to extend its functionality as needed.
type postsDao struct {
	*internal.PostsDao
}

var (
	// Posts is a globally accessible object for table posts operations.
	Posts = postsDao{internal.NewPostsDao()}
)

// Add your custom methods and functionality below.
